[tool.poetry]
name = "globus-timer-cli"
version = "0.1.0"
description = "CLI for interacting with the timer API"
authors = ["Rudyard Richter <rudyard@globus.org>"]
keywords = [
  "globus",
  "automation",
  "cli"
]
readme = "README.md"
packages = [
    { include = "timer_cli" }
]

[tool.poetry.scripts]
timer = "timer_cli.main:main"

[tool.poetry.dependencies]
python = "^3.6"
typer = "^0.3.1"
fair-research-login = "^0.1.5"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
